name: Export draw.io diagrams

on:
  push:
    branches:
      - main
    paths:
      - 'workflows/*.drawio'

jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Convert draw.io to PNG
        uses: peter-evans/drawio-action@v3
        with:
          source: 'workflows/*.drawio'
          output: 'workflows/'
          format: 'png'
          
      - name: Commit and push the converted PNG
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add workflows/*.png
          git commit -m "Auto-export draw.io diagrams to PNG"
          git push