name: Export draw.io diagrams

on:
  push:
    branches:
      - main
    paths:
      - 'workflows/*.drawio'

jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert draw.io diagrams to PNG
        uses: hg8496/drawio-export@v2.0
        with:
          files: '**/*.drawio'
          format: png
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-export draw.io diagrams"
          git push