name: Export draw.io diagrams

on:
  push:
    branches:
      - main
    paths:
      - 'workflows/*.drawio'

jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Draw.io Export Action
        uses: rlespinasse/drawio-export-action@v2.23.0
        with:
          path: 'workflows'
          format: 'png'
          output: '/'
          transparent: true

      - name: Commit and push the converted PNG
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add workflows/*.png
          git commit -m "Auto-export draw.io diagrams to PNG"
          git push